//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oss48.DB.Cucina
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredienti
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Dolcezza { get; set; }
        public Nullable<int> Sapidita { get; set; }
        public int IdTipoProdotto { get; set; }
        public Nullable<decimal> CostoKg { get; set; }
    }
}
